### ISSUE TITLE
multi action Task cannot be created on k8s

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/aktion#23]
while we can parse a multi action workflow and create a multi step Task. The resulting task cannot be create on k8s.

We need to check the validity of the object.

**Comment by zetaron** [comment]
I came across tektons Pipeline which seems to map quite well to what a workflow file represents. From what I read a pipeline allows for multiple independent graphs to be defined. The pipeline graphs should map well to how GitHub actions and workflows are linked together.

> To be fair, I didn't yet try out either aktion and tekton there might be good reason this won't work as I imagined it above. I am currently just trying to create a link and deepen my understanding of the two projects.

**Comment by sebgoa** [comment]
GitHub Actions workflow have a "Action" dependency syntax with _uses_. That definitely can build a graph, which should be expressed as a Tekton pipeline.

This issue is about the fact that right now the object we create when we have multiple steps in an Action is not a proper Tekton Task.

**Comment by zetaron** [comment]
Ah, thanks for the explanation.
