### ISSUE TITLE
should not error out with no workflow file is present

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/aktion#26]
we should have better error handling:

```
$ aktion create
Error opening file: open main.workflow: no such file or directory
```

I think cobra can react on this and just print the usage.

**Comment by cab105** [comment]
Are you proposing that this error message be replaced with a usage message instead?

**Comment by sebgoa** [comment]
yes. I thought Cobra could do this.

It detects that there are missing args and prints the usage

**Comment by cab105** [comment]
Somewhat. Cobra is configured to use `main.workflow` as the default workflow file if it isn't specified. However I know it can also be configured to prompt for the flag as a required argument as well.

**Comment by cab105** [comment]
A quick google search reveals that there isn't much in the way of flag validation other than adding handlers through Cobra, however I can amend the error message itself to display the failure as well as the usage information.
