### ISSUE TITLE
Handle `uses` better

### ISSUE THREAD

**Issue by cab105** [triggermesh/aktion#3]
Github's Action object has a required parameter called `uses` which can reference one of three things:
  1. A URL to a docker image specified as docker://
  1. A git based repository (with a normal ssh:// or http[s]:// protocol prefix) with a Dockerfile
  1. A directory local to the current git based directory that points to a directory with a Dockerfile

The Knative build-pipeline only knows how to handle Docker images which is great for the first option. However additional steps will need to be embedded to not only retrieve the other two options, but build the temporary container, and store the results in a registry.

**Comment by sebgoa** [comment]
There is an example of doing a docker build with `Task` in: https://github.com/triggermesh/pipeline-tasks/tree/master/nodejs-riff-example

**Comment by cab105** [comment]
Will be closing this issue in lieu of the fix being merged and #27 opened to address some of the related fallout.
