### ISSUE TITLE
Port github action language

### ISSUE THREAD

**Issue by cab105** [triggermesh/aktion#35]
The original repo for github actions has been moved back into a private space.  We'll need to update aktion to support the new syntax.

**Comment by maxandersen** [comment]
and news/plans on this ?

**Comment by cab105** [comment]
This is still a major thing that needs to be done, and is a work in
progress.

**Comment by maxandersen** [comment]
any prs to follow/contribute to ?

**Comment by antoineco** [comment]
Ref. https://github.com/hashicorp/terraform-github-actions/issues/40#issue-481911943

The parser code previously maintained by GitHub has now been removed, so if we want to continue using HCL we have to create our own. Fortunately this is quite straightforward. If the structure of each block is static (like it seems to be in this project), the `hclsimple` package of the HCL toolkit can infer the schema directly from the HCL file being parsed. See example at [hashicorp/hcl](https://github.com/hashicorp/hcl#hcl).
