### ISSUE TITLE
Add an `apply`

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/aktion#4]
while we can do:

```
aktion pipeline -f main.workflow | kubectl apply -f -
```

We probably need a `aktion apply -f main.workflow` which posts the translated objects directly.

The tricky part is actually to read the kubeconfig file to get the k8s credentials

https://github.com/triggermesh/tm/blob/master/pkg/client/client.go#L101

**Comment by cab105** [comment]
Merged.
